version: '3'

services:
  licenseservice:
    build: .
    image: ostock/licenses-service:0.0.1-SNAPSHOT
    container_name: license-api
    ports:
      - '8088:8088'
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
         - "licensingservice"

networks:
    backend:
      driver: bridge
